//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnASP_NETWEBFORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.ReplyComments = new HashSet<ReplyComment>();
        }
    
        public int CommentID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string NameUserComment { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> DateComment { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<ReplyComment> ReplyComments { get; set; }
    }
}
