//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnASP_NETWEBFORM {
    
    
    public partial class Default {
        
        /// <summary>
        /// Slider_Image control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DoAnASP_NETWEBFORM.Slider_Image Slider_Image;
        
        /// <summary>
        /// Sidebar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DoAnASP_NETWEBFORM.Sidebar Sidebar;
    }
}
