//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnASP_NETWEBFORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplyComment
    {
        public int ReplyCommentID { get; set; }
        public Nullable<int> CommentID { get; set; }
        public string NameUserReply { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> DateReply { get; set; }
    
        public virtual Comment Comment { get; set; }
    }
}
